name = "vikadan-tamilnadu"
desc = "vikadan tamilnadu feed"
group = "vikadan"
schedule = "every 5 minutes"
[record]
    sourceUri ="http://rss.vikatan.com/feeds/tamilagam_news.rss"
    [[record.preprocessor]]
        name="http:get"
            [record.preprocessor.params]
                "useCache" = false
    [[record.preprocessor]]
        name="toRssFeed"
    [[record.preprocessor]]
        name="pluck"
            [record.preprocessor.params]
                "field" = "Items"

    [[record.field]]
        name= "Title"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Title"

    [[record.field]]
        name= "Content"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Content"
        [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = "3939 "
                    "new" = "&#39;&#39;"
        [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = "39 "
                    "new" = "&#39;"
                    
     [[record.field]]
        name= "PublishedDate"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="regexp:select"
                [record.field.processor.params]
                    "selectors" = ['Published:<time.*?dateTime="(?P<data>[^"]+)']
                    
    [[record.field]]
        name= "ThumbImageUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Description"
        [[record.field.processor]]
            name="regexp:select"
                [record.field.processor.params]
                    "selectors" = ['<img[^>]+src="(?P<data>[^"]+)']

    [[record.field]]
        name= "Category"
        [[record.field.processor]]
            name="constant"
                [record.field.processor.params]
                    "value" = "Tamilnadu"

     [[record.field]]
        name= "SourceUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"