
[[feed]]
    url = "http://rss.dinamalar.com/?cat=ara1"
    origin = "dinamalar"
    defaultCategory = "politics"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
        # selectorType = "regexp"
        # selector = "<a[^>]+href='(?P<Data>[^']+)"


[[feed]]
    url = "http://rss.dinamalar.com/?cat=pot1"
    origin = "dinamalar"
    defaultCategory = "general"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "http://rss.dinamalar.com/?cat=sam1"
    origin = "dinamalar"
    defaultCategory = "incidents"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "http://rss.dinamalar.com/?cat=kut1"
    origin = "dinamalar"
    defaultCategory = "justice"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "http://rss.dinamalar.com/tamilnadunews.asp"
    origin = "dinamalar"
    defaultCategory = "tamilnadu"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "http://rss.dinamalar.com/Delhinews.asp"
    origin = "dinamalar"
    defaultCategory = "delhi"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "http://rss.dinamalar.com/?cat=INL1"
    origin = "dinamalar"
    defaultCategory = "world"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "http://rss.dinamalar.com/?cat=business1"
    origin = "dinamalar"
    defaultCategory = "business"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    url = "https://cinema.dinamalar.com/rss.php"
    origin = "dinamalar"
    defaultCategory = "cinema"
    dateLayouts = ["01/02/06", "January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [[feed.publishedDateExtractors]]
        sourceField = "Published"
        scrapingRequired = false


[[feed]]
    url = "https://sports.dinamalar.com/rss/Cricket"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    url = "https://sports.dinamalar.com/rss/Football"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    url = "https://sports.dinamalar.com/rss/Tennis"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    url = "https://sports.dinamalar.com/rss/Hockey"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    url = "https://sports.dinamalar.com/rss/Badminton"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    url = "https://sports.dinamalar.com/rss/other-sports"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2016"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"
