name = "dinamalar-cricket"
desc = "dinamalar cricket feed"
group = "dinamalar"
schedule = "every 5 minutes"
[record]
    sourceUri ="https://sports.dinamalar.com/rss/Cricket"
    [[record.preprocessor]]
        name="http:get"
            [record.preprocessor.params]
                "useCache" = false
    [[record.preprocessor]]
        name="toRssFeed"
    [[record.preprocessor]]
        name="pluck"
            [record.preprocessor.params]
                "field" = "Items"

    [[record.field]]
        name= "Title"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Title"

    [[record.field]]
        name= "Content"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="css:remove"
                [record.field.processor.params]
                    "selectors" = ["script", "style"]
        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = ["body > div.midbg.float-fix > div.left-box-container.float-fix > div > div.articlesub-cat-mid-rp"]
        [[record.field.processor]]
            name="regexp:remove"
                [record.field.processor.params]
                    "selectors" = ['class="[^"]+"', 'style="[^"]+"']

     [[record.field]]
        name= "PublishedDate"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="regexp:select"
                [record.field.processor.params]
                    "selectors" = ['article:published_time.*content="(?P<data>[^"]+)']
    [[record.field]]
        name= "ThumbImageUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Description"
        [[record.field.processor]]
            name="regexp:select"
                [record.field.processor.params]
                    "selectors" = ["<img[^>]+src='(?P<data>[^']+)"]

    [[record.field]]
        name= "Category"
        [[record.field.processor]]
            name="constant"
                [record.field.processor.params]
                    "value" = "Sports"

     [[record.field]]
        name= "SourceUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"