name = "dinamalar-politics"
desc = "dinamalar politics feed"
group = "dinamalar"
schedule = "every 5 minutes"
[record]
     sourceUri ="https://www.bbc.co.uk/news"
     [[record.preprocessor]]
        name="http:get"
            [record.preprocessor.params]
                "useCache" = false

     [[record.preprocessor]]
        name="css:select"
            [record.preprocessor.params]
                "selectors" = ["#nw-c-topstories-domestic"]

     [[record.preprocessor]]
        name="css:selectEach"
            [record.preprocessor.params]
                "selectors" = [".gs-c-promo-body a.gs-c-promo-heading"]
    
     [[record.preprocessor]]
        name="split"
    
     [[record.preprocessor]]
        name="regexp:select"
            [record.preprocessor.params]
                "selectors" = ["href=\"(?P<data>[^\"]*)"]
	
     [[record.preprocessor]]
        name="combine"

    [[record.field]]
        name= "Content"
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true

        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = [".story-body"]