sourceName = "puthiyathalaimurai"
source ="http://feeds.feedburner.com/Puthiyathalaimurai_Politics_News?format=xml"
sourceType= "rss/atom"
category = "tamilnadu"
schedule = "every 5 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "rssAtomField"

    [[record.field]]
            name= "Description"
            [record.field.collectorInfo]
                type= "rssAtomField"
                [record.field.collectorInfo.parameters]
                    "source" = "Content"

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "rssAtomField"
         [[record.field.transformersInfo]]
            transformer="empty"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Published"
            [[record.field.transformersInfo]]
                transformer="replace"
                [record.field.transformersInfo.parameters]
                    "old" = "+00:00"
                    "new" = ""
            [[record.field.transformersInfo]]
                transformer="parseDate"
                [record.field.transformersInfo.parameters]
                    "layout" = "2006-01-02T15:04:05"
                    "location" = "Asia/Kolkata"
                    "fallbackValue"="transformer:utcNow"

    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "GUID"

    [[record.field]]
    name= "ThumbImageUrl"
    [record.field.collectorInfo]
        type= "rssAtomField"
        [record.field.collectorInfo.parameters]
            "source" = "Content"
        [[record.field.transformersInfo]]
            transformer="regexp"
            [record.field.transformersInfo.parameters]
                "expr" = "<img[^>]+src=\"(?P<data>[^\"]+)"
                "fallbackValue"=""
   