sourceName = "puthiyathalaimurai"
source ="http://feeds.feedburner.com/Puthiyathalaimurai_Viral_Videos?format=xml"
sourceType= "rss/atom"
category = "viralvideo"
schedule = "every 5 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "rssAtomField"

    [[record.field]]
            name= "Description"
            [record.field.collectorInfo]
                type= "rssAtomField"
                [record.field.collectorInfo.parameters]
                    "source" = "Content"

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "rssAtomField"
         [[record.field.transformersInfo]]
            transformer="empty"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "PublishedParsed"

    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "GUID"

    [[record.field]]
    name= "ThumbImageUrl"
    [record.field.collectorInfo]
        type= "rssAtomField"
        [record.field.collectorInfo.parameters]
            "source" = "Content"
        [[record.field.transformersInfo]]
            transformer="regexp"
            [record.field.transformersInfo.parameters]
                "expr" = "<img[^>]+src=\"(?P<data>[^\"]+)"
                "fallbackValue"=""
   