[[feed]]
    url = "http://rss.vikatan.com/feeds/sports_news.rss"
    origin = "vikadan"
    defaultCategory = "sports"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false