sourceName = "dinamalar"
source ="https://cinema.dinamalar.com/rss.php"
sourceType= "rss/atom"
category = "cinema"
schedule = "every 5 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "value"

    [[record.field]]
        name= "Description"
        [record.field.collectorInfo]
            type= "empty"

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "empty"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "value"
            [record.field.collectorInfo.parameters]
                "source" = "Published"
        [[record.field.transformersInfo]]
            transformer="parseDate"
            [record.field.transformersInfo.parameters]
                "layout"= "01/02/06"
        [[record.field.transformersInfo]]
            transformer="utcMidnightToNow"
        

    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "value"
            [record.field.collectorInfo.parameters]
                "source" = "Link"
    [[record.field]]
    name= "ThumbImageUrl"
    [record.field.collectorInfo]
        type= "regexp"
        [record.field.collectorInfo.parameters]
            "source" = "Description"
            "expr" = "<img[^>]+src='(?P<data>[^']+)"
   