allowedOrigins =["vikadan", "dinamalar"]
# allowedOrigins =["vikadan"]

[[feed]]
    name = "dinamalar_politics"
    url = "http://rss.dinamalar.com/?cat=ara1"
    origin = "dinamalar"
    defaultCategory = "politics"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
        # selectorType = "regexp"
        # selector = "<a[^>]+href='(?P<Data>[^']+)"


[[feed]]
    name = "dinamalar_general_pot1"
    url = "http://rss.dinamalar.com/?cat=pot1"
    origin = "dinamalar"
    defaultCategory = "general"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name = "dinamalar_incidents_sam1"
    url = "http://rss.dinamalar.com/?cat=sam1"
    origin = "dinamalar"
    defaultCategory = "incidents"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name = "dinamalar_justice_kut1"
    url = "http://rss.dinamalar.com/?cat=kut1"
    origin = "dinamalar"
    defaultCategory = "justice"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name = "dinamalar_tamilnadu"
    url = "http://rss.dinamalar.com/tamilnadunews.asp"
    origin = "dinamalar"
    defaultCategory = "tamilnadu"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name = "dinamalar_delhi"
    url = "http://rss.dinamalar.com/Delhinews.asp"
    origin = "dinamalar"
    defaultCategory = "delhi"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name = "dinamalar_world"
    url = "http://rss.dinamalar.com/?cat=INL1"
    origin = "dinamalar"
    defaultCategory = "world"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name="dinamalar_business"
    url = "http://rss.dinamalar.com/?cat=business1"
    origin = "dinamalar"
    defaultCategory = "business"

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false

[[feed]]
    name="dinamalar_cinema"
    url = "https://cinema.dinamalar.com/rss.php"
    origin = "dinamalar"
    defaultCategory = "cinema"
    dateLayouts = ["01/02/06", "January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [[feed.publishedDateExtractors]]
        sourceField = "Published"
        scrapingRequired = false


[[feed]]
    name="dinamalar_sports_cricket"
    url = "https://sports.dinamalar.com/rss/Cricket"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    name = "dinamar_sports_football"
    url = "https://sports.dinamalar.com/rss/Football"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    name="dinamalar_sports_tennis"
    url = "https://sports.dinamalar.com/rss/Tennis"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    name = "dinamalar_sport_hockey"
    url = "https://sports.dinamalar.com/rss/Hockey"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    name="dinamalar_sports_badminton"
    url = "https://sports.dinamalar.com/rss/Badminton"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"


[[feed]]
    name = "dinamalar_sports_others"
    url = "https://sports.dinamalar.com/rss/other-sports"
    origin = "dinamalar"
    defaultCategory = "sports"
    dateLayouts = ["January 2, 2006"]

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src='(?P<Data>[^']+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Description"
        scrapingRequired = false

    [[feed.publishedDateExtractors]]
        sourceField = "Title"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "(?P<Data>(ஜனவரி|பெப்ரவரி|மார்ச்|ஏப்ரல்|மே|ஜூன்|ஜூலை|ஆகஸ்ட்|செப்டம்பர்|அக்டோபர்|நவம்பர்|டிசம்பர்)[ ]{1,2}[0-9]{1,2},[ ]{1,2}[0-9]{2,4})"



[[feed]]
    url = "http://rss.vikatan.com/feeds/politics_news.rss"
    origin = "vikadan"
    defaultCategory = "politics"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false


[[feed]]
    url = "http://rss.vikatan.com/feeds/entertainment.rss"
    origin = "vikadan"
    defaultCategory = "cinema"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false

[[feed]]
    url = "http://rss.vikatan.com/feeds/sports_news.rss"
    origin = "vikadan"
    defaultCategory = "sports"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false

[[feed]]
    url = "http://rss.vikatan.com/feeds/world_news.rss"
    origin = "vikadan"
    defaultCategory = "world"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false


[[feed]]
    url = "http://rss.vikatan.com/feeds/tamilagam_news.rss"
    origin = "vikadan"
    defaultCategory = "general"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false

[[feed]]
    url = "http://rss.vikatan.com/feeds/india_news.rss"
    origin = "vikadan"
    defaultCategory = "general"
    dateLayouts = ["2006-01-02 15:04:05"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Description"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false

[[feed]]
    url = "http://rss.vikatan.com/feeds/short_news_uc.rss"
    origin = "vikadan"
    defaultCategory = "general"
    dateLayouts = ["Mon, 02 Jan 2006 15:04:05 IST"]
    forceReparsePublishedDate = true
    reparsePublishedDateDefaultLocation = "Asia/Kolkata"
    useCurrentDateTimeWhenPubDateMissing = true

    [feed.itemThumbImageExtractor]
        sourceField = "Content"
        scrapingRequired = true
        selectorType = "regexp"
        selector = "<img[^>]+src=\"(?P<Data>[^\"]+)"

    [feed.itemUrlExtractor]
        sourceField = "Link"
        scrapingRequired = false
    
    [feed.shortContentExtractor]
        sourceField = "Content"
        scrapingRequired = false