sourceName = "vikadan"
source ="http://rss.vikatan.com/feeds/india_news.rss"
sourceType= "rss/atom"
category = "india"
schedule = "every 5 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "rssAtomField"

    [[record.field]]
        name= "Description"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Content"

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "rssAtomField"
        [[record.field.transformersInfo]]
            transformer="empty"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Published"
        [[record.field.transformersInfo]]
            transformer="parseDate"
             [record.field.transformersInfo.parameters]
                "layout" = "2006-01-02 15:04:05"
                "location" = "Asia/Kolkata"
                "fallbackValue"="transformer:utcNow"
                    
    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Link"

    [[record.field]]
    name= "ThumbImageUrl"
    [record.field.collectorInfo]
        type= "rssAtomField"
        [record.field.collectorInfo.parameters]
            "source" = "Description"
        [[record.field.transformersInfo]]
            transformer="regexp"
            [record.field.transformersInfo.parameters]
                "expr" = "<img[^>]+src=\"(?P<data>[^\"]+)"
                "fallbackValue"=""
   