sourceName = "dinamalar"
source ="http://rss.dinamalar.com/?cat=ara1"
sourceType= "rss/atom"
category = "politics"
schedule = "every 30 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "value"

    [[record.field]]
        name= "Description"
        [record.field.collectorInfo]
            type= "value"

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "value"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "value"
            [record.field.collectorInfo.parameters]
                "source" = "PublishedParsed"

    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "value"
            [record.field.collectorInfo.parameters]
                "source" = "Link"
    [[record.field]]
        name= "ThumbImageUrl"
        [record.field.collectorInfo]
            type= "regexp"
            [record.field.collectorInfo.parameters]
                "source" = "Description"
                "expr" = "<img[^>]+src='(?P<data>[^']+)"
   