name = "oneindia-tamil-news"
desc = "oneindia tamil news feed"
group = "oneindia"
schedule = "every 5 minutes"
[record]
    sourceUri ="https://tamil.oneindia.com/rss/tamil-fb.xml"
    [[record.preprocessor]]
        name="http:get"
            [record.preprocessor.params]
                "useCache" = false
    [[record.preprocessor]]
        name="rssatom:parse"
    [[record.preprocessor]]
        name="pluck"
            [record.preprocessor.params]
                "field" = "Items"

    [[record.field]]
        name= "Title"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Title"

    [[record.field]]
        name= "Content"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['(?P<data>[^?]+)']
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="css:remove"
                [record.field.processor.params]
                    "selectors" = ["#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > nav", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > h1", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.io-category", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.author-detail.clearfix", "#d_social_media", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > p.mat_promo", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.city-article-list-wrap","#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.io-author","#notification-articleblock",".deepLinkPromo"]
        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = ["#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt"]
        [[record.field.processor]]
            name="css:remove"
                [record.field.processor.params]
                    "selectors" = ["script", "style"]
        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = ["body"]
        [[record.field.processor]]
            name="regexp:remove"
                [record.field.processor.params]
                    "selectors" = ['class="[^"]+"', 'style="[^"]+"']
                   
     [[record.field]]
        name= "PublishedDate"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Published"
        [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = ['\+00:00']
                    "new" = ""
        [[record.field.processor]]
            name="date:parse"
                [record.field.processor.params]
                    "layout" = "Mon, 02 Jan 2006 15:04:05 -0700"
                    
    [[record.field]]
        name= "ThumbImageUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['(?P<data>[^?]+)']
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="css:remove"
                [record.field.processor.params]
                    "selectors" = ["#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > nav", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > h1", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.io-category", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.author-detail.clearfix", "#d_social_media", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > p.mat_promo", "#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.city-article-list-wrap","#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt > div.io-author","#notification-articleblock",".deepLinkPromo"]
        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = ["#container > section > div > div.leftpanel > article > div > div.oiMiddleMain > div.oi-article-lt"]
        [[record.field.processor]]
            name="css:remove"
                [record.field.processor.params]
                    "selectors" = ["script", "style"]
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['<img[^>]+src="(?P<data>[^"]+)']

    [[record.field]]
        name= "Category"
         [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
    [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['/news/(?P<data>[^/]+)']
    [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = ["washington", "london", "international"]
                    "new"= "World"
    [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = ["delhi", "bangalore", "mumbai", "india", "lucknow", "patna", "thiruvananthapuram"]
                    "new"= "India"
    [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = ["chennai", "madurai", "nagercoil", "karur", "virudhunagar", "coimbatore", "kanyakumari", "vellore", "sivagangai", "trichirappalli", "puducherry", "thanjavur", "tuticorin", "tiruppur", "villupuram", "tamilnadu"]
                    "new"= "Tamilnadu"
    [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = ["^[a-z]+.*$"]
                    "new"= "Others"
    
     [[record.field]]
        name= "SourceUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['(?P<data>[^?]+)']