name = "puthiyathalaimurai-sports"
desc = "puthiyathalaimurai sports feed"
group = "puthiyathalaimurai"
schedule = "every 5 minutes"
[record]
    sourceUri ="http://feeds.feedburner.com/Puthiyathalaimurai_Sports_News?format=xml"
    [[record.preprocessor]]
        name="http:get"
            [record.preprocessor.params]
                "useCache" = false
    [[record.preprocessor]]
        name="rssatom:parse"
    [[record.preprocessor]]
        name="pluck"
            [record.preprocessor.params]
                "field" = "Items"

    [[record.field]]
        name= "Title"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Title"

    [[record.field]]
        name= "Content"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Content"
                   
     [[record.field]]
        name= "PublishedDate"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Published"
        [[record.field.processor]]
            name="regexp:replace"
                [record.field.processor.params]
                    "old" = ['\+00:00']
                    "new" = ""
        [[record.field.processor]]
            name="date:parse"
                [record.field.processor.params]
                    "layout" = "2006-01-02T15:04:05"
                    "location" = "Asia/Kolkata"
                    
    [[record.field]]
        name= "ThumbImageUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Content"
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['<img[^>]+src="(?P<data>[^"]+)']

    [[record.field]]
        name= "Category"
        [[record.field.processor]]
            name="constant"
                [record.field.processor.params]
                    "value" = "Sports"

     [[record.field]]
        name= "SourceUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "GUID"