sourceName = "dinamalar"
source ="http://rss.dinamalar.com/?cat=sam1"
sourceType= "rss/atom"
category = "incidents"
schedule = "every 5 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "rssAtomField"

    [[record.field]]
            name= "Description"
            [record.field.collectorInfo]
                type= "rssAtomField"
                [record.field.collectorInfo.parameters]
                    "source" = "Link"
            [[record.field.transformersInfo]]
                transformer="scrape"
                [record.field.transformersInfo.parameters]
                        "selectorType" = "custom"
                        "custom:selector" = "content"
                        "custom:focusSelectors" = ["#mvp-content-wrap", "#columns > div:nth-child(8) > div.row > div.col-sm-12.col-md-8"]

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "rssAtomField"
         [[record.field.transformersInfo]]
            transformer="empty"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Published"
            [[record.field.transformersInfo]]
                transformer="parseDate"
                [record.field.transformersInfo.parameters]
                    "layout" = "Mon, 02 Jan 2006 15:04:05 -0700"
                    "fallbackValue"="transformer:utcNow"

    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Link"

    [[record.field]]
    name= "ThumbImageUrl"
    [record.field.collectorInfo]
        type= "rssAtomField"
        [record.field.collectorInfo.parameters]
            "source" = "Description"
        [[record.field.transformersInfo]]
            transformer="regexp"
            [record.field.transformersInfo.parameters]
                "expr" = "<img[^>]+src='(?P<data>[^']+)"
                "fallbackValue"=""
   