sourceName = "dinamalar"
source ="https://sports.dinamalar.com/rss/Football"
sourceType= "rss/atom"
category = "sports"
schedule = "every 5 minutes"
[record]
    [[record.field]]
        name= "Title"
        [record.field.collectorInfo]
            type= "rssAtomField"

    [[record.field]]
        name= "Description"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Link"
        [[record.field.transformersInfo]]
            transformer="scrape"
            [record.field.transformersInfo.parameters]
                    "selectorType" = "custom"
                    "custom:selector" = "content"
                    "custom:focusSelectors" = ["body > div.midbg.float-fix > div.left-box-container.float-fix > div > div.articlesub-cat-mid-rp"]
                    "custom:fallbackImageSelector" = "body > div.midbg.float-fix > div.left-box-container.float-fix > div > div.articlesub-cat-mid-rp > div > div:nth-child(4) > div.article-left-sub-cat1 > div > span > img"

    [[record.field]]
        name= "Content"
        [record.field.collectorInfo]
            type= "rssAtomField"
        [[record.field.transformersInfo]]
            transformer="empty"

    [[record.field]]
        name= "PublishedDate"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Published"
        [[record.field.transformersInfo]]
            transformer="utcNow"
                    
    [[record.field]]
        name= "SourceUrl"
        [record.field.collectorInfo]
            type= "rssAtomField"
            [record.field.collectorInfo.parameters]
                "source" = "Link"

    [[record.field]]
    name= "ThumbImageUrl"
    [record.field.collectorInfo]
        type= "rssAtomField"
        [record.field.collectorInfo.parameters]
            "source" = "Description"
        [[record.field.transformersInfo]]
            transformer="regexp"
            [record.field.transformersInfo.parameters]
                "expr" = "<img[^>]+src='(?P<data>[^']+)"
                "fallbackValue"=""
   