name = "dinamalar-politics"
desc = "dinamalar politics feed"
group = "dinamalar"
schedule = "every 5 minutes"
[record]
    sourceUri ="http://rss.dinamalar.com/?cat=ara1"
    [[record.preprocessor]]
        name="http:get"
            [record.preprocessor.params]
                "useCache" = false
    [[record.preprocessor]]
        name="rssatom:parse"
    [[record.preprocessor]]
        name="pluck"
            [record.preprocessor.params]
                "field" = "Items"

    [[record.field]]
        name= "Title"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Title"

    [[record.field]]
        name= "Content"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = ["#mvp-content-wrap", "#columns > div:nth-child(8) > div.row > div.col-sm-12.col-md-8"]
        [[record.field.processor]]
            name="css:remove"
                [record.field.processor.params]
                    "selectors" = ["script", "style", "#colour-selector", "#st-1"]
        [[record.field.processor]]
            name="css:select"
                [record.field.processor.params]
                    "selectors" = ["body"]
        [[record.field.processor]]
            name="regexp:remove"
                [record.field.processor.params]
                    "selectors" = ['class="[^"]+"', 'style="[^"]+"']
        [[record.field.processor]]
            name="regexp:remove"
                [record.field.processor.params]
                    "selectors" = ["Advertisement"]

     [[record.field]]
        name= "PublishedDate"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"
        [[record.field.processor]]
            name="http:get"
                [record.field.processor.params]
                    "useCache" = true
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ['article:published_time.*content="(?P<data>[^"]+)']
    [[record.field]]
        name= "ThumbImageUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Description"
        [[record.field.processor]]
            name="regexp:selectOne"
                [record.field.processor.params]
                    "selectors" = ["<img[^>]+src='(?P<data>[^']+)"]

    [[record.field]]
        name= "Category"
        [[record.field.processor]]
            name="constant"
                [record.field.processor.params]
                    "value" = "India"

     [[record.field]]
        name= "SourceUrl"
        [[record.field.processor]]
            name="pluck"
                [record.field.processor.params]
                    "field" = "Link"